apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdbion-movieservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdbion-movieservice
  template:
    metadata:
      labels:
        app: imdbion-movieservice
    spec:
      containers:
        - name: imdbion-movieservice
          image: albion99/movieservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__MovieContext
              valueFrom:
                secretKeyRef:
                  name: imdbion-movieservice-secrets
                  key: MovieContext
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: imdbion-movieservice
spec:
  type: LoadBalancer
  selector:
    app: imdbion-movieservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
