apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdbion-movieservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdbion-movieservice-deployment
  template:
    metadata:
      labels:
        app: imdbion-movieservice-deployment
    spec:
      containers:
        - name: imdbion-movieservice-deployment
          image: albion99/movieservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__MovieContext
              valueFrom:
                secretKeyRef:
                  name: imdbion-movieservice-secrets
                  key: MovieContext
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: imdbion-movieservice
spec:
  selector:
    app: imdbion-movieservice-deployment
  ports:
    - port: 80
